version: '3'
services:
  nginx:
    image: "nginx:alpine"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service
      - kibana
    ports:
      - "80:80"
  service:
    build:
      context: ./
    depends_on:
      - database
      - elasticsearch
  database:
    image: "postgres:alpine"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=omega32
    volumes:
      - dbdatavol:/var/lib/postgresql/data
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0"
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  kibana:
    image: "docker.elastic.co/kibana/kibana-oss:6.1.0"
    volumes:
      - ./kibana/:/usr/share/kibana/config:ro
    depends_on:
      - elasticsearch
#  pgadmin:
#    image: "dpage/pgadmin4"
#    depends_on:
#      - database
#    ports:
#      - "5000:80"
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=hans@kilianconsult.dk
#      - PGADMIN_DEFAULT_PASSWORD=omega32
volumes:
  dbdatavol:
    driver: local