version: '3'
services:
  service:
    image: "hans"
    depends_on:
      - database
      - elasticsearch
    ports:
      - "80:80"
  database:
    image: "postgres:alpine"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=omega32
    volumes:
      - dbdatavol:/var/lib/postgresql/data
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0"
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  kibana:
    image: "docker.elastic.co/kibana/kibana-oss:6.1.0"
    volumes:
      - ./kibana/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
#  pgadmin:
#    image: "dpage/pgadmin4"
#    depends_on:
#      - database
#    ports:
#      - "5000:80"
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=hans@kilianconsult.dk
#      - PGADMIN_DEFAULT_PASSWORD=omega32
volumes:
  dbdatavol:
    driver: local