version: '3'
services:
  service:
    image: "hans"
    depends_on:
      - database
    ports:
      - "80:80"
  database:
    image: "postgres:alpine"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=omega32
    volumes:
      - dbdatavol:/var/lib/postgresql/data
#  pgadmin:
#    image: "dpage/pgadmin4"
#    depends_on:
#      - database
#    ports:
#      - "5000:80"
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=hans@kilianconsult.dk
#      - PGADMIN_DEFAULT_PASSWORD=omega32
volumes:
  dbdatavol:
    driver: local